// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/5/10 22:14:04
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/chenlei/001_AI/personax/web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/chenlei/001_AI/personax/web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/chenlei/001_AI/personax/web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/chenlei/001_AI/personax/web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/chenlei/001_AI/personax/web/plugins/**/*.{js,ts,mjs}","/home/chenlei/001_AI/personax/web/composables/**/*.{js,ts,mjs}","/home/chenlei/001_AI/personax/web/utils/**/*.{js,ts,mjs}","/home/chenlei/001_AI/personax/web/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/chenlei/001_AI/personax/web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/chenlei/001_AI/personax/web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/chenlei/001_AI/personax/web/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;